### ISSUE TITLE
advance_action() vs make_action()

### ISSUE THREAD

**Issue by hashbangCoder** [Marqt/ViZDoom#71]
Hi,
Im not sure if this is the right place to post this, but I couldn't find any other forum for vizdoom. 
I find advance_action functionality to be quite confusing. From what I understand make_action(action,_tics_) repeats the action _tics_ times and advance_action allows you to perform a **specific** action during skipped frames using set_action() and returns state info and updated frame after.  So the **only** difference between the two is you can specify which action you want the skipped frames to perform?

Assuming the correct way to use advance_action is : 

- 1. make_action(_desiredAction_)         //Perform action as per policy
- 2. set_action(_skipAction_)                  //set action for skipped frames
- 3. advance_action(tics, True, True)      //skip frames, update state, render frame

I have the following questions. Lets take the example of basic.py with set_action("Shoot") and advance_action(5,True,True) added to the code like shown above: 

-  Shoot is repeated 5 times after every _desiredAction_ ? But the skipped frames are not rendered. And state numbers are 1,3,5,...  ?

- What do update_state and render_only. do exactly? You can't seem to get state info of skipped frames. And why is state info even required for skipped frames? 

Also, how do you perform no_action (noOps) ?
 
Thanks in advance! Any clarification would be helpful.

**Comment by ebonyclock** [comment]
https://groups.google.com/forum/#!forum/vizdoom woulb be better for this kind of questions in the future but since the question landed here I'll answer it.

* set_state(action) sets the action to be performed (not only for the skipped frames)
* advance_action actualy performs this action (that was set with set_action)
* make_action is a convenient wrapper for set_action(action) + advance_actions(tics,True,True) and it's  fully equivalent

So the main difference is that you can specify render_only and update_state parameters in advance_action.

When update_state is set to True, state is updated after the last tic in the action so:
advance_action(5,True,True) will update the state/rewards etc after the 5th tic so it is not equivalent to using advance_action(1,True,True) 5 times (cause this updates the state with each action/tic). render_only causes the screen buffer to be rendered (not displayed) and available via get_game_screen(). Why might it all be useful? E.g. for recording a video including the skipped frames. It might be also useful in other situations so we didn't won't to limit possibilities.

This combination:
*set_action("Shoot") and advance_action(5,True,True) 
will result in shooting 5 times, and updating the set_action("Shoot") and advance_action(5,True,True) state after the 5th shot fired.
 
Noop is actually setting all buttons to False/0 sousing e.g. 3 buttons to perform Noop use:
make_action([0,0,0]) / make_action([False,False,False]). If you are lazy you can use an empty list since it will be filled with required number of 0 so:
make_action([]) is a NoOp.

I hope that it'll clear something, if not sufficiently ask more!.
