### ISSUE TITLE
Possible bug in game.set_button_max_value

### ISSUE THREAD

**Issue by glebreutov** [Marqt/ViZDoom#90]
In my code I have a following button config:

```
game.add_available_button(Button.TURN_LEFT_RIGHT_DELTA)
game.add_available_button(Button.ATTACK)
game.set_button_max_value(Button.TURN_LEFT_RIGHT_DELTA, rand.randrange(-100, 100))
game.make_action([True, False])

```

But, player always turns right, no matter what value was supplied to set_button_max_value.

**Comment by ebonyclock** [comment]
To get something clear: after the config you made TURN_LEFT_RIGHT_DELTA button expects integer input from range [-100,100]. Negative values should turn left, positive right, 0 means no turn. When you make an action with True it parses it to 1 so it should turn one degree right each timestep. That's the expected behavior. So then, the question is whether you are using only True and False or negative values also?

**Comment by glebreutov** [comment]
Thanks, this code works as expected:
`    game.make_action([rand.randrange(-2, 2), 0])`

But, why do game need set_button_max_value then?

**Comment by ebonyclock** [comment]
Heh, github let me edit your comment and I accidentally did it, sorry ... strange.

Game doesn't need to set_button_max_value, it's optional. Having it unconstrained makes it possible to turn 180 degrees in a single tic and I imagine that sb would want to forbid it.

**Comment by glebreutov** [comment]
Thanks! Now all clear!
